name: CI

on:
  push:
    branches: [main, lint]
  pull_request:
    branches: [main, lint]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flake8 bandit pytest coverage

      - name: Set PYTHONPATH for custom pylint plugin
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run pylint
        run: |
          pylint lib_ml --rcfile=./lib-ml/.pylintrc

      - name: Run flake8
        run: |
          flake8 lib_ml --config=./lib-ml/.flake8

      - name: Run bandit
        run: |
          bandit -r lib_ml -x tests -s B101,B104 -lll

      - name: Run pytest with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=80
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
