name: Release lib-ml

on: 
    push:
        tags: 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.2

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install setuptools wheel twine

            - name: Build package
              run: |
                  python setup.py sdist bdist_wheel
                
            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  dist/*.whl
                  dist/*.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}